### ISSUE TITLE
New item is not displayed if slug is not created

### ISSUE THREAD

**Issue by agairing** [pticon91/directus-extensions-dcb-tree-view-bundle#3]
Hello,
this is really a nice extension for directus :-).
I'm not sure if I missed something in the setup.

Steps:
* create tree view for existing collection using the default that the meta collection is created -> all is good
* create new item for the existing collection and don't create a "Meta" entry with a value for the slug field

--> The new item is not displayed in the tree view. You can switch back to the table view and see the new item.

Is this intended?

**Comment by digital-cowboy-91** [comment]
Hi, the meta is mandatory. If you don't create a meta - the page will not have relation with meta table and that's why it will not appear in the list (meta field should be preset to not be null so the page is not saved without it). Extension uses meta to save all required sorting information there and then uses this collection to generate tree-view.

When you create a new meta, you don't have to fill any information there unless you need to. Slug is being generated automatically.
