### ISSUE TITLE
Filters are ignored

### ISSUE THREAD

**Issue by essalkniro** [pticon91/directus-extensions-dcb-tree-view-bundle#4]
When using the tree view, set filters are not taken into account. Instead, all records are displayed.

**Comment by digital-cowboy-91** [comment]
Hi, thank you for reporting. This is expected behaviour. User should get a warning when trying to use Search or Filter, [see code](https://github.com/digital-cowboy-91/directus-extensions-dcb-tree-view-bundle/blob/61744f5c3e1f304ed8ee0735cfdb2c864d467b6b/src/tree-view/index.ts#L174). Until I figure out how to properly render data, these features will not be supported.
